/* tslint:disable */
/* eslint-disable */
/**
 * netuserapi
 * This api is used for the management of users created for the netelek web apps
 *
 * The version of the OpenAPI document: 1.0.10
 * Contact: devsupport@remig.co.za
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

